import 'package:flutter/material.dart';

class MenuScreen extends StatefulWidget {
  @override
  _MenuScreenState createState() => _MenuScreenState();
}

class _MenuScreenState extends State<MenuScreen> {
  @override
  Widget build(BuildContext context) {
    return null;
  }
}

// class _MenuScreenState extends State<MenuScreen> {

//   final DateTime now = new DateTime.now();


//   @override
//   Widget build(BuildContext context) {
//     return Scaffold(
//         body: Center(
//           child: (
//             ListView(
//               children: [
//                 Card(
                  
//                   Text()
//                 ),
//               ]
//             )
//           ),
//       ),
//     );
//   }
// }

/*Widget quickCalls = Container(
  child: Card(
    child: Padding(
      padding: const EdgeInsetsDirectional.fromSTEB(
        12,
        12,
        12,
        12,
      ),*/