import 'package:flutter/material.dart';

class MenuScreen extends StatefulWidget {
  
  _MenuScreenState createState() => _MenuScreenState();
}

class _MenuScreenState extends State<MenuScreen> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Center(
        child: Text(
          'Under Construction!',
          style: TextStyle(fontSize: 25, color: Colors.white, fontWeight: FontWeight.bold),
        ),
      ),
    );
  }
}

/*Widget quickCalls = Container(
  child: Card(
    child: Padding(
      padding: const EdgeInsetsDirectional.fromSTEB(
        12,
        12,
        12,
        12,
      ),*/